### ISSUE TITLE
All Artifact skill trees (major bug) - 3.0.20/3.0.20h

### ISSUE THREAD

**Issue by whyspyy** [nvb-uy/ProminenceII-HasturianEra#1] opened 2024-11-27 18:49 UTC
It's long but may you read everything cuz it's important imo🙏 
No pictures or anything cuz the tests are really simple to make (explained later)

• Basically, artifact skill trees are **NOT increasing your damage at all**.
Most of the artifact skill trees have increase in dmg of some sort. Attack damage%/Damage from artifact%/Damage%/Dmg per broken soul stack%...
But in reality, **all these increase are not working**. As long as it affects your damage, it won't work, even on the artifact weapon itself.
BUT there is an exception and it's **Supernova**. Everything is working fine on it and its skill tree is even working no matter the weapon you play. It's the only artifact weapon in this case.

• **A simple test** is by making a new world in creative mode, then taking an artifact weapon, and finally comparing your damage **before any changes** and **after you level up your artifact tree to the maximum**. You'll see that on any artifact weapon (except Supernova), you do the **same dmg before and after**. Which is obviously not normal.
If you want to you can also do further testing, let's say with a full build. If you test your dmg **before** activating a dmg increase node from an artifact tree, and **after** activating it, you'll see it's the same result.

• **For example :** if you take the artifact tree from **Thunderwrath** and increase it to the maximum, you will do the same amount of dmg. Even while playing Thunderwrath weapon itself.
Same for **A'zhar** and its tree, the dmg is not actually increasing based on the number of broken soul stacks, the dmg is still the same. And even more important, numbers are not changing while spamming auto-attacks so it really is not related to the concept of stacks of broken soul. Which shouldn't be the case.
• And if you take **Supernova** and its skill tree, all its dmg% increase are working perfectly fine. While playing supernova or any other weapon.

• Also i want to add that some of these "increase" said in artifact trees are shown in your stats in **"prominent.artifact_damage"** as it should be, but they are not actually working. A'zhar increase with broken soul stacks are shown here.
While Supernova increase is shown directly in the **"physical dmg"** stat AND is working.
Same for any other stats that are not about increasing your numbers. They are shown in their respective stats AND are working. For example, **HP% nodes** in any artifact skill tree are shown in the **"Max health"** stat and are working.

**Comment by nvb-uy** [comment] 2024-11-27 23:27
Known, it's currently top priority and will be hopefully released by the next update. It's caused by another mod overwriting the damage modifications

**Comment by nvb-uy** [comment] 2024-12-10 23:58
Fixed on 3.0.21

**Closed by nvb-uy** 2024-12-10 23:58 UTC
